#!/bin/bash

echo compiling $1...
gcc $1.c -o $1 -lm
success=$?


# echo "success is $success"

if [ $success -eq 0 ]; then
	echo finished compiling
	read -p "Run? (y/n) " response
	if [ $response == "y" ]; then

		echo running...
		./$1

	fi
else
	echo "Compilation unsuccesful :("
fi
